### ISSUE TITLE
Config / Documentation / Init - Write descriptions, and a custom schema parser for yaml+comments

### ISSUE THREAD

**Issue by v1kko** [CarbonCollective/fusion-dUQtools#120]
the init command should create a simple configuration, with only the most important fields exposed.
```
workspace:
  root:
plot:
  plots:
create:
  sampler:
    n_samples:
 matrix:
     - ids: 
       operator:
       values
```

- [x] also have a `--full` flag to get all the configurable options
- [x] Create a custom yaml writer to parse schemas to get documented config files
