### ISSUE TITLE
Split template from IMAS data

### ISSUE THREAD

**Issue by stefsmeets** [CarbonCollective/fusion-dUQtools#178]
As a user,
I want to select my jetto template settings and IMAS template data seperately,
So I can use the same jetto config with multiple IMAS data.

Currently, we read the IMAS handle from the jetto settings, which is a good default. For some use cases, it is useful to have this split.

**Comment by stefsmeets** [comment]
Something like:

```yaml
template:
  settings: /pfs/work/docs/jetto/runs/duqtools_template
  data:
    user: ...
    db: ...
    shot: ...
    run: ...
```

If `data==None`, grab IMAS handle from settings.
