### ISSUE TITLE
Removing the prefix in merge tools

### ISSUE THREAD

**Issue by v1kko** [CarbonCollective/fusion-dUQtools#218]
The full paths make it less confusing for new people

**Comment by stefsmeets** [comment]
Since I'm working on this anyway, I'm going for something like this:

```
  ids_to_merge:
  - ids: core_profiles
    base_grid: profiles_1d/0/grid/rho_tor_norm
    paths:
    - profiles_1d/$i/t_i_average
    - profiles_1d/$i/zeff
```

That will also make it possible to specify multiple IDS paths, i.e. other than `core_profiles`.
