### ISSUE TITLE
allow constant time interval with varying start time as a matrix variable

### ISSUE THREAD

**Issue by v1kko** [CarbonCollective/fusion-dUQtools#285]
This relates quite closely to coupled Scans from the jetto_tools https://jintrac.gitlab.io/jetto-pythontools/config.html?#coupled-scans

- [x] We have to look if we can leverage the Scan API in any way here
- [ ] Make a way to plot the data as if they have an uniform starting time (better than simply taking the step index)
- [x] A possible config file might eventually look something like this:

```yaml
variables:
- name: t_start
- name: t_end
create:
  template: template_model
  data:
    imasdb: test
    run_in_start_at: 7000
    run_out_start_at: 8000
  sampler:
    method: latin-hypercube
    n_samples: 3
  dimensions:
    - variable: t_start
      operator: copyto
      values: [0.1, 0.2, 0.3]
      coupled_to: t_end
    - variable: t_end
      operator: copyto
      values: [1.1, 1.2, 1.3]
```
