### ISSUE TITLE
Separate variables and/or config files to reduce complexity of the config file

### ISSUE THREAD

**Issue by v1kko** [CarbonCollective/fusion-dUQtools#313]

**Comment by stefsmeets** [comment]
Related: #311

**Comment by stefsmeets** [comment]
I think this is one we should tackle first, there are a few other issues that depend on this working well.

**Comment by v1kko** [comment]
An idea where we can use multiple config files, and with the following rule of thumb:
- each file should be able to be run with the `-c` this means some duplication of some keys (variables, workspace, system) 

config.yml (toplevel):
```yaml
create: create.yml
submit: 
  system: jetto-duqtools
  workspace: /pfs/work/<user>/jetto/runs
merge: merge.yml
```
I did not put `submit:` in its own file, because it contains very little information.


A self-contained create.yml, that can also be used with the -c option, notably it now contains the workspace, system and variables key:
```yaml
create:
  system: jetto-pythontools
  workspace: /pfs/work/<user>/jetto/runs
  dimensions:
  - values: [ 1.1, 1.2, 1.3 ]
    operator: multiply
    scale_to_error: false
    variable: t_i_average
  variables: variables.yaml
 ```
It might be easier to put `variables`, `workspace`, `system` at toplevel so it matches better with what we already have.

A self-contained variables.yaml:
```yaml
- name: rho_tor_norm
  type: IDS-variable
  ids: core_profiles
  path: profiles_1d/*/grid/rho_tor_norm
  dims: [ time, x]
- name: major_radius 
  type: jetto-variable 
  lookup: 
    doc: Reference major radius (R0) 
    name: major_radius 
    type: float 
    keys: 
    - file: jetto.jset 
      field: EquilEscoRefPanel.refMajorRadius 
    - file: jetto.in 
      field: RMJ 
      section: NLIST1
```

- other seperated out config  files can be created in the same manner (merge, plot)
